apiVersion: v1
kind: Service
metadata:
labels:
  app: zlmediakit
name: zlmediakit
ports:
- name: rtmp
  nodePort: 1935
  port: 1935
  protocol: TCP
  targetPort: 1935
- name: rtsp
  nodePort: 554
  port: 554
  protocol: TCP
  targetPort: 554
- name: http
  nodePort: 8080
  port: 80
  protocol: TCP
  targetPort: 80
selector:
  app: zlmediakit
type: NodePort
