version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    command: "/usr/local/bin/etcd --config-file=/usr/local/etc/etcd/etcd.yml"
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /usr/local/docker-volumes/etcd/data:/var/etcd
      - /usr/local/docker-volumes/etcd/config:/usr/local/etc/etcd
    # restart: always
    restart: "on-failure:3"
  
  # etcd:
  #   container_name: etcd
  #   image: quay.io/coreos/etcd:3.5.12
  #   environment:
  #     - ETCD_NAME=etcd-1
  #     - ETCD_DATA_DIR=/var/etcd
  #     - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
  #     - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
  #     - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
  #     - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
  #     - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
  #     - ETCD_INITIAL_CLUSTER=etcd-s=http://0.0.0.0:2380
  #     - ETCD_INITIAL_CLUSTER_STATE=new
  #     - ETCD_LOGGER=zap
  #     - ETCD_LOG_LeveL=info
  #     - TZ="Asia/Shanghai"
  #   volumes:
  #     - /usr/local/docker-volumes/etcd/data:/var/etcd
  #   ports:
  #     - "2379:2379"
  #     - "2380:2380"
  #   restart: always
