apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: etcd
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      initContainers:

      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.12
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /var/lib/redis
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          command: [ "redis-server" ,"/usr/local/etc/redis/redis.conf" ]
          env:
            - name: TZ
              value: "Asia/Shanghai"
            # 允许无身份验证访问
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            # 实例名称
            - name: ETCD_NAME
              value: etcd
            # 数据目录
            - name: ETCD_DATA_DIR
              value: /var/lib/etcd
            # client 流量监听地址
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            # 该 member 向外部通告的客户端 url 列表
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            # peer 流量监听地址
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://0.0.0.0:2380"
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config