# 自签名颁发机构
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kube-system
  labels:
    app: selfsigned-issuer
spec:
  selfSigned: {}
---
# 自签名根证书
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-root-cert
  namespace: kube-system
  labels:
    app: selfsigned-root-cert
spec:
  isCA: true
  commonName: Example SelfSigned Root CA
  secretName: selfsigned-root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - Example Inc.
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  # 该格式不允许d(days)后缀，
  # 必须使用s(seconds),m(minutes)和h(hours)代替
  duration: 87600h # 10year 有效期
  renewBefore: 360h # 15d 到期前续订
  dnsNames:
    - "example.io"
    - "*.example.io"
---
# 集群内证书颁发机构
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  labels:
    app: selfsigned-cluster-issuer
spec:
  ca:
    secretName: selfsigned-root-ca