# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#  name: selfsigned-issuer
#  namespace: kube-system
# spec:
#  selfsigned: {}

# ---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  namespace: kube-system
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-root-cert
  namespace: kube-system
  labels:
    app: selfsigned-root-cert
spec:
  isCA: true
  commonName: Example SelfSigned Root CA
  secretName: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - Example Inc.
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io