apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`whoami.example.io`) || PathPrefix(`/whoami`)
      services:
        - name: whoami
          port: 80
          namespace: default
          kind: Service

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: default
spec:
  isCA: false
  commonName: Example Self Signed - WHOAMI
  secretName: whoami-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 72h # 3d
  subject:
    organizations:
      - Example .Inc
  dnsNames:
    - whoami.example.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-websecure
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.example.io`) || PathPrefix(`/whoami`)
      services:
        - name: whoami
          port: 80
          namespace: default
          kind: Service
  tls:
    secretName: whoami-secret
