apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/port: "9153"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.43.0.10
  clusterIPs: [10.43.0.10]
  ports:
  - name: dns
    port: 53
    nodePort: 53
    protocol: UDP
  #- name: dns-tcp
  #  port: 53
  #  protocol: TCP
  #- name: metrics
  #  port: 9153
  #  protocol: TCP
  ipFamilyPolicy: SingleStack
  type: NodePort

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    log
  devops.server: |
    example.io {
        errors
        health
        ready
        cache 30
        hosts {
            # 注意此处127.0.0.1需修改未宿主机IP
            127.0.0.1 whoami.example.io 
            127.0.0.1 harbor.example.io 
            127.0.0.1 traefik.example.io # traefik dashboard 
            127.0.0.1 gitea.example.io
            127.0.0.1 drone.example.io
            127.0.0.1 sonar.example.io
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        reload
        loadbalance
    }