apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: kube-dns-route
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  entryPoints:
  - coredns
  routes:
  - match: HostSNI(`*`)
    services:
    - name: kube-dns
      port: 53
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    log
  devops.server: |
    example.io {
        errors
        health
        ready
        cache 30
        hosts {
            # 注意此处127.0.0.1需修改未宿主机IP
            127.0.0.1 whoami.example.io 
            127.0.0.1 harbor.example.io 
            127.0.0.1 traefik.example.io # traefik dashboard 
            127.0.0.1 gitea.example.io
            127.0.0.1 drone.example.io
            127.0.0.1 sonar.example.io
            127.0.0.1 tekton.example.io
            127.0.0.1 argocd.example.io
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        reload
        loadbalance
    }