apiVersion: v1
kind: PersistentVolume
metadata:
  name: emqx-pv
  namespace: emqx
  labels:
    app: emqx
spec:
  storageClassName: emqx-persistent-storage
  capacity:
    storge: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/lib/emqx/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc
  labels:
    app: emqx
spec:
  storageClassName: emqx-persistent-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storge: 5Gi