apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-tcp
  namespace: emqx
  labels:
    app: emqx
spec:
  entryPoints:
  - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: emqx
      port: 1883

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-dashboard-websecure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`emqx.example.io`) && (PathPrefix(`/`) || PathPrefix(`/api`))
      services:
        - name: dashboard
          port: 18083
  tls:
    secretName: emqx-dashbord-secret