apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-tcp
  namespace: emqx
spec:
  entryPoints:
  - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: emqx
      port: 1883

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
 name: emqx-dashoard-websecure
 namespace: emqx
 annotations:
   traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
 entryPoints:
   - websecure
 routes:
   - match: Host(`emqx.example.io`) && PathPrefix(`/`)
     kind: Rule
     services:
       - name: dashboard
         namespace: emqx
         passHostHeader: true
         port: 18083
 tls:
   secretName: emqx-dashboard-secret