apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-tcp
  namespace: emqx
spec:
  entryPoints:
  - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: emqx
      port: 1883

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
 name: emqx-dashoard-web
 namespace: emqx
 annotations:
   traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
   traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`emqx.example.io`) && PathPrefix(`/`)
      services:
        - name: emqx-dashboard
          port: 18083

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
 name: emqx-dashoard-websecure
 namespace: emqx
 annotations:
   traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
   traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`emqx.example.io`) && PathPrefix(`/`)
      services:
        - name: emqx-dashboard
          port: 18084
          #namespace: emqx
          #kind: Service
  tls:
    secretName: emqx-secret
