apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-tcp
  namespace: emqx
  labels:
    app: redis
spec:
  entryPoints:
  - mqtt
  routes:
  - match: HostSNI(`*`)
    services:
    - name: redis
      port: 6379

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-dashboard-websecure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`emqx.example.io`) && (PathPrefix(`/`) || PathPrefix(`/api`))
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-dashbord-secret