apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-pvc
  labels:
    app: emqx
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi