apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-pvc
  labels:
    app: seaweed
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
