apiVersion: v1
kind: Service
metadata:
  name: seaweed
  namespace: seaweed
  labels:
    app: seaweed
spec:
  selector:
    app: seaweed
  type: NodePort
  ports:
    - name: master-port
      port: 9333
      nodePort: 9333
      targetPort: 9333

    - name: show-port
      port: 8080
      nodePort: 8080
      targetPort: 8080
