apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drone-server
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - name: drone-server
        image: drone/drone:2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: drone-persistent-storage
          mountPath: /data
        envFrom:
        - configMapRef:
            name: drone-server-config
      volumes:
      - name: drone-persistent-storage
        persistentVolumeClaim:
          claimName: drone-server-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
  labels:
    app: drone-runner
spec:
  selector:
    matchLabels:
      app: drone-runner
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
      - name: drone-runner
        image: drone/drone-runner-kube:latest
        envFrom:
        - configMapRef:
            name: drone-runner-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-secrets
  namespace: drone
  labels:
    app: drone-secrets
spec:
  selector:
    matchLabels:
      app: drone-secrets
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-secrets
    spec:
      containers:
      - name: drone-secrets
        image: drone/kubernetes-secrets:latest
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: drone-secrets-config

