apiVersion: v1
kind: Namespace
metadata:
  name: drone

# ---

# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata: 
#   name: drone-issuer
#   namespace: drone
#   labels:
#     app: drone-issuer
# spec:
#   ca:
#     secretName: root-ca
#     secretNamespace: kube-system

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-cert
  namespace: drone
  labels:
    app: drone-cert
spec:
  secretName: drone-secret
  duration: 8760h # 1year
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: ""
  dnsNames:
  - drone.example.io