apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-server-config
  namespace: devops
  labels:
    app: drone-server
data:
  DRONE_SERVER_HOST: "drone.example.io"
  DRONE_SERVER_PORT: ":80"
  DRONE_SERVER_PROTO: http
  DRONE_GITEA_SERVER: "https://gitea.example.io"
  DRONE_GITEA_CLIENT_ID: "" 
  DRONE_GITEA_CLIENT_SECRET: ""
  DRONE_RPC_SECRET: "" 
  DRONE_LOGS_TRACE: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner-config
  namespace: devops
  labels:
    app: drone-runner
data:
  DRONE_RPC_HOST: "https://drone.example.io"
  DRONE_RPC_SECRET: ""
