apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-server-config
  namespace: drone
  labels:
    app: drone-server
data:
  TZ: Asia/Shanghai
  DRONE_SERVER_HOST: "drone.example.io"
  DRONE_SERVER_PORT: ":80"
  DRONE_SERVER_PROTO: https
  DRONE_GITEA_SERVER: https://gitea.example.io
  DRONE_GITEA_SKIP_VERIFY: "true"  # 使用自签名时跳过证书校验
  DRONE_GITEA_CLIENT_ID: "" # Gitea添加集成登录ClientId
  DRONE_GITEA_CLIENT_SECRET: "" # Gitea添加集成登录ClientSecret
  DRONE_RPC_SECRET: "3841baff0f63aed0d69c7a4f1eff2a9d"  # openssl rand -hex 16
  #DRONE_DEBUG: "true"
  DRONE_DATABASE_DRIVER: postgres
  DRONE_DATABASE_DATASOURCE: postgres://drone:drone@postgres.postgres.svc.cluster.local:5432/drone?sslmode=disable
  DRONE_LOGS_TRACE: "true"
  #DRONE_USER_CREATE: "username:admin,admin:true,token:3841baff0f63aed0d69c7a4f1eff2a9d"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner-config
  namespace: drone
  labels:
    app: drone-runner
data:
  DRONE_RPC_HOST: "https://drone-server:80"
  DRONE_RPC_SECRET: "3841baff0f63aed0d69c7a4f1eff2a9d" # 与drone-server配置中 DRONE_RPC_SECRET 保持一致
  DRONE_NAMESPACE_DEFAULT: drone
  DRONE_SECRET_PLUGIN_ENDPOINT: "http://drone-secrets:3000"
  DRONE_SECRET_PLUGIN_TOKEN: "2ddd3070c4b7c6bc4671c266e4be9e75" # openssl rand -hex 16
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-secrets-config
  namespace: drone
  labels:
    app: drone-secrets
data:
  SECRET_KEY: "2ddd3070c4b7c6bc4671c266e4be9e75" # 与drone-runner配置中 DRONE_SECRET_PLUGIN_TOKEN 保持一直