apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-server-pvc
  namespace: drone
  labels:
    app: drone-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
