apiVersion: v1
kind: Service
metadata:
  labels:
    app: drone-server
  name: drone-server
  namespace: devops
spec:
  ports:
  - port: 80
    name: http
    nodePort: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: drone-server
  type: NodePort
  
#---
#
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: drone-ingress-websecure
#  namespace: devops
#  annotations:
#    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
#spec:
#  entryPoints:
#    - websecure
#  routes:
#    - match: Host(`drone.example.io`) && PathPrefix(`/`)
#      kind: Rule
#      services:
#        - name: drone-server
#          passHostHeader: true
#          port: 80
#  tls:
#    secretName: drone-tls