apiVersion: v1
kind: Service
metadata:
  labels:
    app: drone-server
  name: drone-server
  namespace: devops
spec:
  ports:
  - port: 80
    nodePort: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: drone-server
  type: NodePort
