apiVersion: v1
kind: Service
metadata:
  name: drone
  namespace: devops
  labels:
    app: drone
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: drone-ingress
  namespace: drone
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/drone`)
      kind: Rule
      services:
        - name: drone
          port: 8080
