apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-server-config
  namespace: devops
  labels:
    app: drone-server
data:
  TZ: Asia/Shanghai
  DRONE_SERVER_HOST: "drone.example.io"
  DRONE_SERVER_PORT: ":80"
  DRONE_SERVER_PROTO: http
  DRONE_GITEA_SERVER: "https://gitea.example.io"
  DRONE_GITEA_CLIENT_ID: "" 
  DRONE_GITEA_CLIENT_SECRET: ""
  DRONE_RPC_SECRET: ""  # openssl rand hex 16
  #DRONE_DEBUG: "true"
  DRONE_DATABASE_DRIVER: postgres
  DRONE_DATABASE_DATASOURCE: postgres://drone:drone@192.168.0.2:5432/drone?sslmode=disable
  DRONE_LOGS_TRACE: "true"
  DRONE_USER_CREATE: username:gitea_admin,admin,true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner-config
  namespace: devops
  labels:
    app: drone-runner
data:
  DRONE_RPC_HOST: "https://drone.example.io"
  DRONE_RPC_SECRET: "" # 与上边 DRONE_RPC_SECRET 保持一致