apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone
  namespace: devops
  labels:
    app: drone
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path