apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-server-config
  namespace: devops
  labels:
    app: drone-server
data:
  TZ: Asia/Shanghai
  DRONE_SERVER_HOST: "192.168.0.2:8080"
  DRONE_SERVER_PORT: ":80"
  DRONE_SERVER_PROTO: http
  DRONE_GITEA_SERVER: http://192.168.0.2:3000
  DRONE_GITEA_SKIP_VERIFY: "true" 
  DRONE_GITEA_CLIENT_ID: "" # Gitea添加集成登录ClientId
  DRONE_GITEA_CLIENT_SECRET: "" # Gitea添加集成登录ClientSecret
  DRONE_RPC_SECRET: "3841baff0f63aed0d69c7a4f1eff2a9d"  # openssl rand hex 16
  DRONE_DEBUG: "true"
  DRONE_DATABASE_DRIVER: postgres
  DRONE_DATABASE_DATASOURCE: postgres://drone:drone@postgres:5432/drone?sslmode=disable
  DRONE_LOGS_TRACE: "true"
  #DRONE_USER_CREATE: "username:admin,admin:true,token:3841baff0f63aed0d69c7a4f1eff2a9d"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner-config
  namespace: devops
  labels:
    app: drone-runner
data:
  DRONE_RPC_HOST: "http://drone-server"
  DRONE_RPC_SECRET: "3841baff0f63aed0d69c7a4f1eff2a9d" # 与上边 DRONE_RPC_SECRET 保持一致
