apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drone-cert
  namespace: drone
spec:
  isCA: false
  commonName: "Example drone CI"
  secretName: drone-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 72h # 3d
  subject:
    organizations:
    - Example .Inc
  dnsNames:
  - drone.example.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
 name: drone-ingress-websecure
 namespace: drone
 annotations:
   traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
 entryPoints:
   - websecure
 routes:
   - match: Host(`drone.example.io`) && PathPrefix(`/`)
     kind: Rule
     services:
       - name: drone-server
         passHostHeader: true
         port: 80
 tls:
   secretName: drone-secret