apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
 name: gitea-websecure
 namespace: gitea
 annotations:
   traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
 entryPoints:
   - websecure
 routes:
   - match: Host(`gitea.example.io`) && PathPrefix(`/`)
     kind: Rule
     services:
       - name: gitea-http
         passHostHeader: true
         port: 3000
 tls:
   secretName: gitea-secret