apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: devops
  labels:
    app: gitea
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: gitea
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: devops
  labels:
    app: gitea
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  type: ClusterIP
  