apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
  labels:
    app: gitea
data:
  ENABLE_OPENID_SIGNIN: "false" # 禁用OPENID登录
  DISABLE_REGISTRATION: "true" # 禁用注册
  ENABLE_OPENID_SIGNUP: "false" # 禁用OPENID注册 ENABLE_OPENID_SIGNUP: ! DISABLE_REGISTRATION
  SSH_LISTEN_PORT: "2222"
  SSH_PORT: "22"
  GITEA_APP_INI: /data/gitea/conf/app.ini
  GITEA_CUSTOM: /data/gitea
  GITEA_WORK_DIR: /data
  GITEA_TEMP: /tmp/gitea
  TMPDIR: /tmp/gitea
  HOME: /data/gitea/git
  # Gitea服务器的对外 URL,决定git clone 的根地址  
  # ROOT_URL: ""
  # 服务器域名
  # DOMAIN: ""
  APP_NAME: "Gitea: Git with a cup of tea" # 标题栏显示名称
  HTTP_PORT: "3000"
  RUN_MODE: prod
  DB_TYPE: postgres
  DB_HOST: postgres.postgres.svc.cluster.local:5432
  DB_NAME: gitea
  DB_USER: gitea
  DB_PASSWD: gitea
  REQUIRE_SIGNIN_VIEW: "true" # 仅允许已登录用户查看探索页面 
  ACTIONS_ENABLED: "false"
  
  # GITEA_cache_ADAOTER: redis
  # GITEA_cache_HOST: redis://:macaron@redis.redis.svc.cluster.local/0?pool_size=100&idle_timeout=180s
  # GITEA_session_PROVIDER: redis
  # GITEA_session_CONFIG: redis://:macaron@redis.redis.svc.cluster.local/0?pool_size=100&idle_timeout=180s
  # GITEA_queue_TYPE: redis
  # GITEA_queue_CONN_STR: redis://redis.redis.svc.cluster.local/0