apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.22.0-rootless
        envFrom:
        - configMapRef:
            name: gitea-config
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 3000
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: temp
        - mountPath: /data
          name: gitea-persistent-storage
      restartPolicy: Always
      volumes:
      - name: temp
        emptyDir: {}
      - name: gitea-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-pvc
