apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingress
  namespace: devops
  labels:
    app: gitea
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/gitea`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
