apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: devops
  labels:
    app: gitea
data:
  gitea.ini: |-
APP_NAME = Gitea
RUN_USER = git
RUN_MODE = prod
WORK_PATH = /data

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /tmp/gitea/local-repo

[repository.upload]
TEMP_PATH = /tmp/gitea/uploads

[server]
APP_DATA_PATH = /data
SSH_DOMAIN = 192.168.0.2
HTTP_PORT = 3000
ROOT_URL = http://192.168.0.2:3000/
DISABLE_SSH = false
; In rootless gitea container only internal ssh server is supported
START_SSH_SERVER = true
SSH_PORT = 22
SSH_LISTEN_PORT = 2222
BUILTIN_SSH_SERVER_USER = git
LFS_START_SERVER = true
DOMAIN = 192.168.0.2
LFS_JWT_SECRET = hcWiUyiPoHL2XfS0J771GXXbAMgglOptpYWBWenxlAQ
OFFLINE_MODE = true

[database]
PATH = /data/data/gitea.db
DB_TYPE = postgres
HOST = postgres:5432
NAME = gitea
USER = gitea
PASSWD = gitea
SCHEMA =
SSL_MODE = disable
LOG_SQL = false

[session]
PROVIDER_CONFIG = /data/data/sessions
PROVIDER = file

[picture]
AVATAR_UPLOAD_PATH = /data/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/data/repo-avatars

[attachment]
PATH = /data/data/attachments

[log]
ROOT_PATH = /data/data/log
MODE = console
LEVEL = info

[security]
INSTALL_LOCK = true
SECRET_KEY =
REVERSE_PROXY_LIMIT = 1
REVERSE_PROXY_TRUSTED_PROXIES = *
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MjA1MTM0ODN9.AkbIl-6OLShNwKz_QzNwcdNx7L-frdlhkgZW3BLRqXs
PASSWORD_HASH_ALGO = pbkdf2

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = false
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL = true
ALLOW_ONLY_EXTERNAL_REGISTRATION = false
ENABLE_CAPTCHA = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = false
DEFAULT_ENABLE_TIMETRACKING = true
NO_REPLY_ADDRESS = noreply.localhost

[lfs]
PATH = /data/git/lfs

[mailer]
ENABLED = true
SMTP_ADDR = 
SMTP_PORT = 
FROM = 
USER = 
PASSWD =

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = false

[cron.update_checker]
ENABLED = false

[repository.pull-request]
DEFAULT_MERGE_STYLE = merge

[repository.signing]
DEFAULT_TRUST_MODEL = committer

[oauth2]
JWT_SECRET = YtHVHLocIF81KTyG9xUAlryJrWNrsVqXmECtmhQPmOE

