apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: devops
  labels:
    app: gitea
data:
  ENABLE_OPENID_SIGNIN: "false" # 禁用OPENID登录
  DISABLE_REGISTRATION: "true" # 禁用注册
  ENABLE_OPENID_SIGNUP: "false" # 禁用OPENID注册 ENABLE_OPENID_SIGNUP: ! DISABLE_REGISTRATION
  SSH_LISTEN_PORT: "2222"
  SSH_PORT: "22"
  GITEA_APP_INI: /data/gitea/conf/app.ini
  GITEA_CUSTOM: /data/gitea
  GITEA_WORK_DIR: /data
  GITEA_TEMP: /tmp/gitea
  TMPDIR: /tmp/gitea
  HOME: /data/gitea/git
  # Gitea服务器的对外 URL,决定git clone 的根地址  
  # ROOT_URL: ""
  # 服务器域名
  # DOMAIN: ""
  APP_NAME: "Gitea: Git with a cup of tea" # 标题栏显示名称
  RUN_MODE: prod
  DB_TYPE: postgres
  DB_HOST: postgres:5432
  DB_NAME: gitea
  DB_USER: gitea
  DB_PASSWD: gitea