apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  namespace: devops
  labels:
    app: gitea
spec:
  storageClassName: gitea-persistent-storage
  capacity:
    storge: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/lib/gitea/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: devops
  labels:
    app: gitea
spec:
  storageClassName: gitea-persistent-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storge: 5Gi