expose:
  type: ingress
  tls:
    enabled: false
externalURL: http://192.168.50.249/harbor
persistence:
  enabled: true
  resourcePolicy: "keep"
harborAdminPassword: "Harbor12345"
database:
  type: external
  external:
    host: ""
    port: "5432"
    username: "harbor"
    password: ""
redis:
  type: external
  external:
    addr: ":6379"
    username: ""
    password: ""