apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingress
  namespace: harbor
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/harbor`)
      kind: Rule
      services:
        - name: harbor-portal
          port: 80
