apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        expose:
          default: false
      websecure:
        expose:
          default: true
        nodePort: 443
      traefik:
        expose:
          default: true
        nodePort: 9000
        protocol: TCP
      mqtt:
        port: 1883
        expose:
          default: true
        nodePort: 1883
        protocol: TCP
      redis:
        port: 6379
        expose:
          default: true
        nodePort: 6379
        protocol: TCP
      postgres:
        port: 5432
        expose:
          default: true
        nodePort: 5432
        protocol: TCP
    logs:
      access:
        enabled: true
