apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      traefik:
        port: 8080
        expose: true
        exposedPort: 8080
        protocol: TCP
      redis:
        port: 6379
        expose: true
        exposedPort: 6379
        protocol: TCP
      postgres:
        port: 5432
        expose: true
        exposedPort: 5432
        protocol: TCP
    logs:
      access:
        enabled: true
