# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: traefik-secret
#   namespace: kube-system
# spec:
#   secretName: traefik-dashbord-secret
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   dnsNames:
#     - traefik.example.io
# ---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: traefik-dashboard-issuer
  namespace: kube-system
  labels:
    app: traefik-dashboard-issuer
spec:
  ca:
    secretName: root-ca

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: kube-system
spec:
  secretName: traefik-dashbord-secret
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - traefik.example.io