apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        port: 80 
        expose:
          default: true
        nodePort: 80
        protocol: TCP
        #proxyProtocol:
        #  insecure: true
        redirectTo:
         port: websecure
      websecure:
        port: 443
        expose:
          default: true
        nodePort: 443
        protocol: TCP
      # traefik:
      #   port: 9000
      #   expose:
      #     default: true
      #   nodePort: 9000
      #   protocol: TCP
      coredns:
        port: 53
        expose:
          default: true
          #default: false
          #internal: true
        nodePort: 53
        protocol: UDP
      mqtt:
        port: 1883
        expose:
          default: true
          #default: false
          #internal: true
        nodePort: 1883
        protocol: TCP
      redis:
        port: 6379
        expose:
          default: true
          #default: false
          #internal: true
        nodePort: 6379
        protocol: TCP
      etcd:
        port: 2379
        expose:
          default: true
          #default: false
          #internal: true
      postgres:
        port: 5432
        expose:
          default: true
          #default: false
          #internal: true
        nodePort: 5432
        protocol: TCP
      tdengine:
        port: 6041
        expose:
          default: true
          #default: false
          #internal: true
        nodePort: 6041
        protocol: TCP
    #service:
    #  additionalServices:
    #    internal:
    #      type: LoadBalancer
    #      labels:
    #        traefik-service-label: internal
    logs:
      access:
        enabled: true
