apiVersion: helm.cattle.io/v1
kind: HelmChat
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    ports:
      traefik:
        expose: true
      redis:
        port: 6379
        expose: true
        exposedPort: 6379
        protocol: TCP
      postgres:
        port: 5432
        expose: true
        exposedPort: 5432
        protocol: TCP
    logs:
      access:
        enabled: true
