apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: docker.io/library/registry:latest
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: registry-presistent-storage
          mountPath: /var/lib/registry
          
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: registry-presistent-storage
        persistentVolumeClaim:
          claimName: registry-pvc
         
