apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 5000
      targetPort: registry
  selector:
    app: registry
