apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: devops
  labels:
    app: registry
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
        environment: staging
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    # 账号密码
    auth:
      htpasswd:
        realm: Registry Realm
        path: /etc/registry/passwd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    # 上游代理
    proxy:
      remoteurl: "https://docker.m.daocloud.io"