apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
  labels:
    app: registry
  
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: docker.io/library/registry:latest
        name: registry
        ports:
        - name: registry
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: registry-presistent-storage
          mountPath: /var/lib/registry
        - name: registry-config
          mountPath: /etc/docker/registry
        #- name: tls-secret
        #  mountPath: /etc/docker/registry/tls_secret
        #  readOnly: true
        #env:
        #- name: REGISTRY_HTTP_TLS_CERTIFICATE
        #  value: ""        
        #- name: REGISTRY_HTTP_TLS_KEY
        #  value: ""
        #- name: REGISTRY_AUTH
        #  value: "htpasswd"
        #- name: REGISTRY_AUTH_HTPASSWD_REALM
        #  value: "Registry Realm"
        #- name: REGISTRY_AUTH_HTPASSWD_PATH
        #  value: "/auth/htpasswd"          
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: registry-presistent-storage
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: registry-config
        configMap:
          name: registry-config
      #- name: tls-secret
      #  secret:
      #    secretName: registry-tls
         
