apiVersion: apps/v1
kind: Deployment
metadata:
  name: frps
  namespace: frp
  labels:
    app: frps
spec:
  selector:
    matchLabels:
      app: frps
  template:
    metadata:
      labels:
        app: frps
    spec:
      containers:
      - name: frps
        image: ghcr.io/fatedier/frps:v0.44.0
        command: ["/usr/bin/frps", "-c", "/usr/local/etc/frp/frps.ini"]
        ports:
        - containerPort: 7500
          name: dashboard
          containerPort: 7000
          name: service
        volumeMounts:
        - name: frps-config
          mountPath: /usr/local/etc/frp
      volumes:
      - name: frps-config
        configMap:
          name: frps-config