apiVersion: v1
kind: Service
metadata:
  name: frps
  namespace: frps
  labels:
    app: frps
spec:
  ports:
  - name: service
    port: 7000
    protocol: TCP
    targetPort: 7000
    nodePort: 7000
  - name: dashboard
    port: 7500
    protocol: TCP
    targetPort: 7500
    nodePort: 7500
  selector:
    app: frps
  type: NodePort