apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-qube
  namespace: sonar
  labels:
    app: sonar-qube
spec:
  selector:
    matchLabels:
      app: sonar-qube
  template:
    metadata:
      labels:
        app: sonar-qube
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - image: sonarqube:lts-community
        name: sonar-qube
        envFrom:
        - configMapRef:
            name: sonar-config
        ports:
        - containerPort: 9000 
          name: http
        volumeMounts:
        - name: sonar-storage
          subPath: conf
          mountPath: /opt/sonarqube/conf
        - name: sonar-storage
          subPath: data
          mountPath: /opt/sonarqube/data
        - name: sonar-storage
          subPath: extensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonar-storage
        persistentVolumeClaim:
          claimName: sonar-pvc