apiVersion: v1
kind: Service
meatdata:
  name: sonar-http
  namespace: sonar
  labels:
    app: sonar-http
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sonar-http
  type: ClusterIP