apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: sonar
  labels:
    app: sonar-config
data:
  TZ: "Asia/Shanghai"
  SONAR_JDBC_URL: "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/sonar"
  SONAR_JDBC_USERNAME: "sonar"
  SONAR_JDBC_PASSWORD: "sonar"