apiVersion: v1
kind: ConfigMap
matadata:
  name: sonar-config
  namespace: sonar
  labels:
    app: sonar-config
data:
  TZ: "Asia/Shanghai"
  SONAR_JDBC_URL: "jdbc:postgresql://postgresdb:5432/sonar"
  SONAR_JDBC_USERNAME: "sonar"
  SONAR_JDBC_PASSWORD: "sonar"