apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdengine-pvc
  namespace: tdengine
  labels:
    app: tdengine
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
