apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdengine-pv
  namespace: tdengine
  labels:
    app: tdengine
spec:
  storageClassName: tdengine-persistent-storage
  capacity:
    storge: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/lib/taos/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdengine-pvc
  namespace: tdengine
  labels:
    app: tdengine
spec:
  storageClassName: tdengine-persistent-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storge: 5Gi
