apiVersion: apps/v1
kind: Deployment
metadata:
  name: monibuca
  namespace: monibuca
  labels:
    app: monibuca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monibuca
  template:
    metadata:
      labels:
        app: monibuca
    spec:
      # initContainers:
      #   - name: init-0
      #     image: busybox
      #     imagePullPolicy: IfNotPresent
      #     terminationMessagePath: /dev/termination-log
      #     terminationMessagePolicy: File
      #     command: [ "sysctl", "-w", "net.core.somaxconn=511" ]
      #     securityContext:
      #       privileged: true
      #   - name: init-1
      #     image: busybox
      #     imagePullPolicy: IfNotPresent
      #     terminationMessagePath: /dev/termination-log
      #     terminationMessagePolicy: File
      #     command: [ "sh", "-c", "echo never > /sys/kernel/mm/transparent_hugepage/enabled" ]
      #     securityContext:
      #       privileged: true
      containers:
        - name: monibuca
          image: langhuihui/monibuca:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            # - name: monibuca-config
            #   mountPath: /monibuca
              # subPath: config.yaml
          env:
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - containerPort: 554
              name: rtsp
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        # - name: monibuca-config
        #   configMap:
        #     name: monibuca-config