apiVersion: v1
kind: Service
metadata:
  name: monibuca
  namespace: monibuca
  labels:
    app: monibuca
spec:
  ports:
    - name: rtsp
      port: 554
      nodePort: 554
      targetPort: 554
      protocol: TCP
    - name: http
      port: 8080
      nodePort: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: monibuca
  type: NodePort
