apiVersion: apps/v1
kind: Deployment
metadata:
  name: monibuca
  namespace: monibuca
  labels:
    app: monibuca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monibuca
  template:
    metadata:
      labels:
        app: monibuca
    spec:
      containers:
        - name: monibuca
          image: langhuihui/monibuca:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: monibuca-config
              mountPath: /monibuca/config.yaml
              subPath: config.yaml
          env:
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - containerPort: 554
              name: rtsp
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 4096Mi
              cpu: "20"
            limits:
              memory: 10240Mi
              cpu: "60"
      volumes:
        - name: monibuca-config
          configMap:
            name: monibuca-config
