apiVersion: v1
kind: Service
metadata:
  name: monibuca
  namespace: monibuca
  labels:
    app: monibuca
spec:
  ports:
    - name: rtsp
      port: 554
      nodePort: 554
      targetPort: 554
      protocol: TCP
  selector:
    app: monibuca
  type: NodePort
