apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  storageClassName: mysql-persistent-storage
  capacity:
    storge: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /var/lib/mysql/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: mysql-persistent-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storge: 5Gi