apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-10-15T19-57-03Z
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          - minio server /data --console-address ":5000"
          ports:
          - name: data
            containerPort: 9000
            protocol: TCP
          - name: console
            containerPort: 5000
            protocol: TCP
          volumeMounts:
            - name: minio-persistent-storage
              mountPath: /data
            #- name: minio-config
            #  mountPath: /usr/local/etc/
            #  subPath: minio.conf
      volumes:
        - name: minio-persistent-storage
          persistentVolumeClaim:
            claimName: minio-pvc
        - name: minio-config
          configMap:
            name: minio-config