apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  isCA: false
  commonName: Example ArgoCD
  secretName: argocd-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 72h # 3d
  subject:
    organizations:
    - Example .Ltd
  dnsNames:
  - argocd.example.io.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-websecure
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`argocd.example.io`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: argocd-http
      passHostHeader: true
      port: 443
  tls:
    secretName: argocd-secret