apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tekton-cert
  namespace: tekton-pipelines
spec:
  isCA: false
  commonName: TJ PengAn Tekton Pipelines
  secretName: tekton-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h # 90d
  renewBefore: 72h # 3d
  subject:
    organizations:
    - TJ PengAn .Ltd
  dnsNames:
  - tekton.tjpengan.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-websecure
  namespace: tekton-pipelines
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`tekton.tjpengan.io`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: tekton-dashboard
      passHostHeader: true
      port: 9097
  tls:
    secretName: tekton-secret